port = 4242

# define keybinding to return focus to the sender machine
release_bind = [ "KeyLeftCtrl", "KeyLeftShift", "KeyLeftMeta", "KeyLeftAlt" ]

# IPF-ArchLinux
[[clients]]
position = "bottom"
hostname = "ipf-archlinux"
activate_on_startup = true
ips = ["192.168.0.125"]
enter_hook="/home/rafael/.config/scripts/push-clipboard.sh ipf"