virtual_modifiers:
  - F15
  - F19
  - F21
  - F22

shared:
  terminals: &terminals
    - kitty
    - dropdown_terminal
    - dropdown_python
  scratchpads: &scratchpads
    - dropdown_terminal
    - dropdown_python
    - scrcpy
    - Brave-browser-beta
    - Keymapp
    - keymapp
  emacs-ssh: &emacs-ssh
    - "/.*: emacsclient --create-frame.* --alternate-editor=.*emacs.*/"
    - "/.*: emacsclient -c.* -a .*emacs.*/"
    - "/.*: ecd/"
    - "/.*: ec/"
  browsers: &browsers
    - "/brave.*/"
    - "/firefox.*/"
    - chromium
  cedilla: &cedilla
    - "/brave.*/"
    - chromium

modmap:
  - name: volume control with side-bottom mouse button
    remap:
      BTN_BACK:
        held: F21
        alone: KEY_PAGEDOWN
        alone_timeout_millis: 200
  - name: zoom control with side-top mouse button
    remap:
      BTN_FORWARD:
        held: F22
        alone: KEY_PAGEUP
        alone_timeout_millis: 200
keymap:

  - name: copy/paste/cut - terminal
    application:
      only: *terminals
    remap:
      F16: Ctrl-Shift-x
      F17: Ctrl-Shift-c
      F18: Ctrl-Shift-v



  - name: copy/paste/cut - general
    application:
      not: [Emacs, "/emacs.*/", libreoffice-calc]
    remap:
      F16: Ctrl-x
      F17: Ctrl-c
      F18: Ctrl-v

  - name: Emacs inhabitant
    exact_match: true
    application:
      not: [Emacs, "/emacs.*/"]
    remap:
      # window navigation
      Super_L-left:  { launch: ["swaymsg", "focus", "left"] }
      Super_L-down:  { launch: ["swaymsg", "focus", "down"] }
      Super_L-up:    { launch: ["swaymsg", "focus", "up"] }
      Super_L-right: { launch: ["swaymsg", "focus", "right"] }
      # fullscreen
      Alt_L-Super_L-f:  { launch: ["swaymsg", "fullscreen", "toggle"] }
      # terminal
      Alt_L-Super_L-g:  { launch: ["swaymsg", "exec", "kitty"] }
      # kill window
      Alt_L-Super_L-q:  { launch: ["swaymsg", "exec", "$XDG_CONFIG_HOME/scripts/hide-or-kill.sh"] }



  - name: Window navigation
    exact_match: true
    application:
      only: kitty
    window:
      only: *emacs-ssh
    remap:
      Super_L-left:  [C-w, C-h]
      Super_L-down:  [C-w, C-j]
      Super_L-up:    [C-w, C-k]
      Super_L-right: [C-w, C-l]

  - name: delete next word
    application:
      only: kitty
    remap:
      Ctrl-Shift-Backspace: Ctrl-Delete

  - name: Prev tab
    exact_match: true
    application:
      only: *browsers
    remap:
      Ctrl-space: Shift-Ctrl-Tab
  - name: open browser in private window
    # Firefox
    application:
      only: firefox-developer-edition
    remap:
      Ctrl-Shift-n:
        # remap to C-S-p
        launch: ["bash", "-c", "ydotool key 29:1 42:1 25:1 25:0 42:0 29:0"]

  - name: Prev/Next tab
    exact_match: true
    application:
      only: brave-browser
    window:
      only: ["better onetab - Brave", "Extensions - Brave", "chrome://newtab - Brave", "Chrome Web Store - Brave"]
    remap:
      Shift-N: Alt-Left        # go back
      Shift-E: Ctrl-Tab        # next tab
      Shift-I: Ctrl-Shift-Tab  # previous tab
      Shift-O: Alt-Right       # go forward
      Shift-X: Ctrl-Shift-T    # reopen tab

  - name: cedilla
    application:
      only: *cedilla
    remap:
      F13:
        remap:
          c:       { launch: ["swaymsg", "exec", "sleep 0.1 && echo -n \"ç\" | wl-copy && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0"] }
          Shift-c: { launch: ["swaymsg", "exec", "sleep 0.1 && echo -n \"Ç\" | wl-copy && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0"] }
  - name: forward char / dead_acute
    exact_match: true
    application:
      not: [Emacs, "/emacs.*/"]
    remap:
      F13:
        remap:
          # apostrophe
          F13: [APOSTROPHE, SPACE]
          space: [APOSTROPHE, SPACE]
          # cedilla
          c: [APOSTROPHE, c]
          Shift-c: [APOSTROPHE, Shift-c]
          # lowercase vowels
          a: [APOSTROPHE, a]
          e: [APOSTROPHE, e]
          i: [APOSTROPHE, i]
          o: [APOSTROPHE, o]
          u: [APOSTROPHE, u]
          # uppercase vowels
          Shift-a: [APOSTROPHE, Shift-a]
          Shift-e: [APOSTROPHE, Shift-e]
          Shift-i: [APOSTROPHE, Shift-i]
          Shift-o: [APOSTROPHE, Shift-o]
          Shift-u: [APOSTROPHE, Shift-u]
          # miscellaneous lowercase
          n: [APOSTROPHE, SPACE, n]
          m: [APOSTROPHE, SPACE, m, SPACE]
          r: [APOSTROPHE, SPACE, r]
          s: [APOSTROPHE, SPACE, s, SPACE]
          t: [APOSTROPHE, SPACE, t, SPACE]
          # miscellaneous uppercase
          Shift-n: [APOSTROPHE, SPACE, Shift-n]
          Shift-m: [APOSTROPHE, SPACE, Shift-m, SPACE]
          Shift-r: [APOSTROPHE, SPACE, Shift-r]
          Shift-s: [APOSTROPHE, SPACE, Shift-s, SPACE]
          Shift-t: [APOSTROPHE, SPACE, Shift-t, SPACE]
      Shift-F13:
        remap:
          # double quotes
          F13: [Shift-APOSTROPHE, SPACE]
          space: [Shift-APOSTROPHE, SPACE]
          #Shift-F13: [Shift-APOSTROPHE, SPACE]
          # tilde lowercase
          a: [Shift-GRAVE, a]
          o: [Shift-GRAVE, o]
          n: [Shift-GRAVE, n]
          # tilde uppercase
          Shift-A: [Shift-GRAVE, Shift-A]
          Shift-O: [Shift-GRAVE, Shift-O]
          Shift-N: [Shift-GRAVE, Shift-N]
          # tilde miscellaneous
          Shift-F13: [Shift-GRAVE, SPACE]
          SLASH:     [Shift-GRAVE, SPACE, SLASH]
          DOT:       [Shift-GRAVE, SPACE, SLASH, DOT]
          # tilde paths
          h: [Shift-GRAVE, SPACE, SLASH]
          g: [Shift-GRAVE, SPACE, SLASH, g,i,t, SLASH]
          k: [Shift-GRAVE, SPACE, SLASH, g,i,t, SLASH, k,e,e,b,a,b, SLASH]
          d: [Shift-GRAVE, SPACE, SLASH, g,i,t, SLASH, d,o,t,f,i,l,e,s, SLASH]
          c: [Shift-GRAVE, SPACE, SLASH, DOT, c,o,n,f,i,g, SLASH]
          e: [Shift-GRAVE, SPACE, SLASH, DOT, c,o,n,f,i,g, SLASH, e,m,a,c,s,minus,e,f,s, SLASH]
          s: [Shift-GRAVE, SPACE, SLASH, DOT, c,o,n,f,i,g, SLASH, s,c,r,i,p,t,s, SLASH]
          v: [Shift-GRAVE, SPACE, SLASH, DOT, c,o,n,f,i,g, SLASH, n,v,i,m, SLASH]
          x: [Shift-GRAVE, SPACE, SLASH, DOT, c,o,n,f,i,g, SLASH, x,r,e,m,a,p, SLASH]
          w: [Shift-GRAVE, SPACE, SLASH, DOT, c,o,n,f,i,g, SLASH, w,a,y,b,a,r, SLASH]
          z: [Shift-GRAVE, SPACE, SLASH, DOT, c,o,n,f,i,g, SLASH, z,s,h, SLASH]
          i: [Shift-GRAVE, SPACE, SLASH, DOT, c,o,n,f,i,g, SLASH, s,w,a,y, SLASH]


  - name: navigate through emoji categories
    application:
      only: [emote, Emote]
    remap:
      Shift-N: Ctrl-Shift-Tab  # previous category
      Shift-O: Ctrl-Tab        # next category
      Shift-I: Ctrl-F          # focus search
      Ctrl-n:  left            # arrow left
      Ctrl-e:  down            # arrow down
      Ctrl-i:  up              # arrow up
      Ctrl-o:  right           # arrow right
      # launch script that will:
      #   - copy emoji (S-Enter)
      #   - exit emote (Esc)
      #   - paste according to context
      Enter: { launch: ["swaymsg", "exec", "$XDG_CONFIG_HOME/scripts/emote-paste.sh"] }


  - name: toggle capslock status & update temp file (/tmp/capslock_status.tmp)
    remap:
      CAPSLOCK: { launch: ["swaymsg", "exec", "$XDG_CONFIG_HOME/scripts/capslock_status.sh toggle"] }

  - name: speaker control
    exact_match: true
    remap:
      F15-k: { launch: ["bash", "-c", "amixer -q sset Master toggle"] }
      F15-esc:       { launch: ["bash", "-c", "amixer -q sset Master 0%"] }
      F15-space:     { launch: ["bash", "-c", "amixer -q sset Master 25%"] }
      F15-tab:       { launch: ["bash", "-c", "amixer -q sset Master 50%"] }
      F15-enter:     { launch: ["bash", "-c", "amixer -q sset Master 75%"] }
      F15-backspace: { launch: ["bash", "-c", "amixer -q sset Master 100%"] }
      F15-e:         { launch: ["bash", "-c", "amixer -q sset Master 5%-"] }
      F15-i:         { launch: ["bash", "-c", "amixer -q sset Master 5%+"] }
      Shift-F15-e:   { launch: ["bash", "-c", "amixer -q sset Master 1%-"] }  # not working on IPF laptop due to hardware limitations (key ghosting)
      Shift-F15-i:   { launch: ["bash", "-c", "amixer -q sset Master 1%+"] }
      F15-comma:     { launch: ["bash", "-c", "amixer -q sset Master 1%-"] }
      F15-dot:       { launch: ["bash", "-c", "amixer -q sset Master 1%+"] }
  - name: microphone control
    remap:
      F15-j: { launch: ["bash", "-c", "amixer -q sset Capture toggle"] }
      Alt-F15-esc:       { launch: ["bash", "-c", "amixer -q sset Capture 0%"] }
      Alt-F15-space:     { launch: ["bash", "-c", "amixer -q sset Capture 25%"] }
      Alt-F15-tab:       { launch: ["bash", "-c", "amixer -q sset Capture 50%"] }
      Alt-F15-enter:     { launch: ["bash", "-c", "amixer -q sset Capture 75%"] }
      Alt-F15-backspace: { launch: ["bash", "-c", "amixer -q sset Capture 100%"] }
      F15-u:         { launch: ["bash", "-c", "amixer -q sset Capture 5%-"] }
      F15-y:         { launch: ["bash", "-c", "amixer -q sset Capture 5%+"] }
      Shift-F15-u:       { launch: ["bash", "-c", "amixer -q sset Capture 1%-"] }  # not working on IPF laptop due to hardware limitations (key ghosting)
      Shift-F15-y:       { launch: ["bash", "-c", "amixer -q sset Capture 1%+"] }
  - name: brightness control
    remap:
      F19-esc:       { launch: ["bash", "-c", "brightnessctl set 0%"] }
      F19-space:     { launch: ["bash", "-c", "brightnessctl set 25%"] }
      F19-tab:       { launch: ["bash", "-c", "brightnessctl set 50%"] }
      F19-enter:     { launch: ["bash", "-c", "brightnessctl set 75%"] }
      F19-backspace: { launch: ["bash", "-c", "brightnessctl set 100%"] }
      F19-e:         { launch: ["bash", "-c", "brightnessctl set 5%-"] }
      F19-i:         { launch: ["bash", "-c", "brightnessctl set 5%+"] }
      S-F19-e:       { launch: ["bash", "-c", "brightnessctl set 1%-"] }
      S-F19-i:       { launch: ["bash", "-c", "brightnessctl set 1%+"] }
  - name: opacity control
    exact_match: true
    remap:
      F19-h:       { launch: ["swaymsg", "exec", "$XDG_CONFIG_HOME/scripts/opacity.sh", "current", "dec"] }
      F19-slash:   { launch: ["swaymsg", "exec", "$XDG_CONFIG_HOME/scripts/opacity.sh", "current", "inc"] }
      F19-k:       { launch: ["swaymsg", "exec", "$XDG_CONFIG_HOME/scripts/opacity.sh", "toggle"] }
      S-F19-h:     { launch: ["swaymsg", "exec", "$XDG_CONFIG_HOME/scripts/opacity.sh", "all", "dec"] }
      S-F19-slash: { launch: ["swaymsg", "exec", "$XDG_CONFIG_HOME/scripts/opacity.sh", "all", "inc"] }
  - name: backlit control
    remap:
      F19-d:     { launch: ["swaymsg", "exec", "$XDG_CONFIG_HOME/scripts/keeb-backlit.sh", "toggle"] }
      F19-comma: { launch: ["swaymsg", "exec", "$XDG_CONFIG_HOME/scripts/keeb-backlit.sh", "dec"] }
      F19-dot:   { launch: ["swaymsg", "exec", "$XDG_CONFIG_HOME/scripts/keeb-backlit.sh", "inc"] }

  - name: window navigation from scratchpads
    application:
      only: *scratchpads
    remap:
      Super-Left:  { launch: ["swaymsg", "focus", "output", "left"] }
      Super-Right: { launch: ["swaymsg", "focus", "output", "right"] }

  - name: miscellaneous text - macros (terminal)
    application:
      only: *terminals
    remap:
      # macro
      Alt_R-s: { launch: ["swaymsg", "exec", "sleep 0.1 && echo -n \"$(<$XDG_CONFIG_HOME/macros/address_1)\" | wl-copy && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0"] }
      Alt_R-t: { launch: ["swaymsg", "exec", "sleep 0.1 && echo -n \"$(<$XDG_CONFIG_HOME/macros/address_2)\" | wl-copy && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0"] }
      Alt_R-g: { launch: ["swaymsg", "exec", "sleep 0.1 && echo -n \"$(<$XDG_CONFIG_HOME/macros/address_3)\" | wl-copy && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0"] }
      Alt_R-c: { launch: ["swaymsg", "exec", "sleep 0.1 && echo -n \"$(<$XDG_CONFIG_HOME/macros/zip_code)\"  | wl-copy && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0"] }
      Alt_R-d: { launch: ["swaymsg", "exec", "sleep 0.1 && echo -n \"$(<$XDG_CONFIG_HOME/macros/phone)\"     | wl-copy && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0"] }
      Alt_R-n: { launch: ["swaymsg", "exec", "sleep 0.1 && echo -n \"$(<$XDG_CONFIG_HOME/macros/email_1)\"   | wl-copy && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0"] }
      Alt_R-l: { launch: ["swaymsg", "exec", "sleep 0.1 && echo -n \"$(<$XDG_CONFIG_HOME/macros/email_2)\"   | wl-copy && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0"] }
      Alt_R-u: { launch: ["swaymsg", "exec", "sleep 0.1 && echo -n \"$(<$XDG_CONFIG_HOME/macros/email_3)\"   | wl-copy && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0"] }
      Alt_R-h: { launch: ["swaymsg", "exec", "sleep 0.1 && echo -n \"$(<$XDG_CONFIG_HOME/macros/name)\"      | wl-copy && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0"] }
      Alt_R-i: { launch: ["swaymsg", "exec", "sleep 0.1 && echo -n \"$(<$XDG_CONFIG_HOME/macros/id)\"        | wl-copy && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0"] }

  - name: miscellaneous text - macros
    application:
      not: *terminals
    remap:
      # macro
      Alt_R-s: { launch: ["swaymsg", "exec", "sleep 0.1 && cat $XDG_CONFIG_HOME/macros/address_1 | wl-copy && ydotool key 29:1 47:1 47:0 29:0"] }
      Alt_R-t: { launch: ["swaymsg", "exec", "sleep 0.1 && cat $XDG_CONFIG_HOME/macros/address_2 | wl-copy && ydotool key 29:1 47:1 47:0 29:0"] }
      Alt_R-g: { launch: ["swaymsg", "exec", "sleep 0.1 && cat $XDG_CONFIG_HOME/macros/address_3 | wl-copy && ydotool key 29:1 47:1 47:0 29:0"] }
      Alt_R-c: { launch: ["swaymsg", "exec", "sleep 0.1 && cat $XDG_CONFIG_HOME/macros/zip_code  | wl-copy && ydotool key 29:1 47:1 47:0 29:0"] }
      Alt_R-d: { launch: ["swaymsg", "exec", "sleep 0.1 && cat $XDG_CONFIG_HOME/macros/phone     | wl-copy && ydotool key 29:1 47:1 47:0 29:0"] }
      Alt_R-n: { launch: ["swaymsg", "exec", "sleep 0.1 && cat $XDG_CONFIG_HOME/macros/email_1   | wl-copy && ydotool key 29:1 47:1 47:0 29:0"] }
      Alt_R-l: { launch: ["swaymsg", "exec", "sleep 0.1 && cat $XDG_CONFIG_HOME/macros/email_2   | wl-copy && ydotool key 29:1 47:1 47:0 29:0"] }
      Alt_R-u: { launch: ["swaymsg", "exec", "sleep 0.1 && cat $XDG_CONFIG_HOME/macros/email_3   | wl-copy && ydotool key 29:1 47:1 47:0 29:0"] }
      Alt_R-h: { launch: ["swaymsg", "exec", "sleep 0.1 && cat $XDG_CONFIG_HOME/macros/name      | wl-copy && ydotool key 29:1 47:1 47:0 29:0"] }
      Alt_R-i: { launch: ["swaymsg", "exec", "sleep 0.1 && cat $XDG_CONFIG_HOME/macros/id        | wl-copy && ydotool key 29:1 47:1 47:0 29:0"] }

  - name: miscellaneous text - currency & superscript (terminal)
    application:
      only: *terminals
    remap:
      # currency
      Alt_R-e: { launch: ["swaymsg", "exec", "sleep 0.1 && echo -n \"€\"  | wl-copy && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0"] }
      Alt_R-p: { launch: ["swaymsg", "exec", "sleep 0.1 && echo -n \"£\"  | wl-copy && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0"] }
      Alt_R-y: { launch: ["swaymsg", "exec", "sleep 0.1 && echo -n \"￥\" | wl-copy && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0"] }
      Alt_R-r: { launch: ["swaymsg", "exec", "sleep 0.1 && echo -n \"₽\"  | wl-copy && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0"] }
      # superscript
      Alt_R-a: { launch: ["swaymsg", "exec", "sleep 0.1 && echo -n \"ª\"  | wl-copy && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0"] }
      Alt_R-o: { launch: ["swaymsg", "exec", "sleep 0.1 && echo -n \"º\"  | wl-copy && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0"] }

  - name: miscellaneous text - currency & superscript
    application:
      not: *terminals
    remap:
      # currency
      Alt_R-e: { launch: ["swaymsg", "exec", "sleep 0.1 && echo -n \"€\"  | wl-copy && ydotool key 29:1 47:1 47:0 29:0"] }
      Alt_R-p: { launch: ["swaymsg", "exec", "sleep 0.1 && echo -n \"£\"  | wl-copy && ydotool key 29:1 47:1 47:0 29:0"] }
      Alt_R-y: { launch: ["swaymsg", "exec", "sleep 0.1 && echo -n \"￥\" | wl-copy && ydotool key 29:1 47:1 47:0 29:0"] }
      Alt_R-r: { launch: ["swaymsg", "exec", "sleep 0.1 && echo -n \"₽\"  | wl-copy && ydotool key 29:1 47:1 47:0 29:0"] }
      # superscript
      Alt_R-a: { launch: ["swaymsg", "exec", "sleep 0.1 && echo -n \"ª\"  | wl-copy && ydotool key 29:1 47:1 47:0 29:0"] }
      Alt_R-o: { launch: ["swaymsg", "exec", "sleep 0.1 && echo -n \"º\"  | wl-copy && ydotool key 29:1 47:1 47:0 29:0"] }


#  - name: presentation with pdfpc
#    exact_match: true
#    application:
#      only: pdfpc
#    remap:
#      KEY_R: { launch: ["$XDG_CONFIG_HOME/scripts/obs-tools.py", "--scene", "camera"] }
#      KEY_S: KEY_1
#      KEY_T: { launch: ["$XDG_CONFIG_HOME/scripts/obs-tools.py", "--scene", "presentation"] }
#      KEY_W: { launch: ["$XDG_CONFIG_HOME/scripts/obs-tools.py", "--scene", "scene-4"] }
#      KEY_F: KEY_2
#      KEY_P: { launch: ["$XDG_CONFIG_HOME/scripts/obs-tools.py", "--scene", "scene-6"] }
#      KEY_X: { launch: ["$XDG_CONFIG_HOME/scripts/obs-tools.py", "--scene", "scene-7"] }
#      KEY_C: KEY_3
#      KEY_D: { launch: ["$XDG_CONFIG_HOME/scripts/obs-tools.py", "--scene", "scene-9"] }
#      KEY_B: { launch: ["$XDG_CONFIG_HOME/scripts/obs-tools.py", "--record"] }
#      KEY_G: KEY_MINUS
#      KEY_V: S-EQUAL
#      KEY_Q: KEY_5
#      KEY_A: KEY_4
#      #KEY_Z:
#      KEY_SPACE: KEY_DOWN
#      KEY_ESC: KEY_UP
#      #KEY_TAB:

  - name: LibreOffice custom bindings
    application:
      only: libreoffice-calc
    remap:
      Ctrl-n: left       # navigation
      Ctrl-e: down       # navigation
      Ctrl-i: up         # navigation
      Ctrl-o: right      # navigation
      F16: Ctrl-x        # cut
      F17: Ctrl-Shift-c  # copy
      F18: Ctrl-v        # paste
      Alt-o: Ctrl-o      # open file

  - name: volume control with mouse
    exact_match: true
    remap:
      F21-XDOWNSCROLL: { launch: ["bash", "-c", "amixer -q sset Master 5%-"] }
      F21-XUPSCROLL:   { launch: ["bash", "-c", "amixer -q sset Master 5%+"] }
  - name: zoom control with mouse
    exact_match: true
    remap:
      F22-XDOWNSCROLL: Ctrl-minus
      F22-XUPSCROLL:   Ctrl-Shift-equal
